name: <Dashboard name>
channels:
  - conda-forge
  - nodefaults
dependencies:
  - python=3.9
  # latest version of plotly can be found at https://github.com/plotly/plotly.py/releases .
  # Version is hardcoded to ensure uniformity no matter the platform.
  - plotly=5.5.0
  - pandas=1.3
  - dash=2.0
  - pytest=6.2
  - pylint=2.12
  - black=22.3.0
  - black-jupyter=22.3.0
  - pip=21.3.1
  - pyodbc=4.0.32
  - numpy=1.22.1
  # Some packages not available in Conda Forge, so have to be installed through pip.
  - pip:
    - git+https://github.com/communitiesuk/pkg_gov_uk_dashboards.git@v2.7.0
    - dash[testing]
    - chromedriver-binary-auto
    - gunicorn
