name: plotly_dashboard_template # Replace with your dashboard name
dependencies:
  - python=3.9
  - pip
  - pip:
    - -r requirements.txt 
    # getting packages from pip with a requirements file allows dependabot to update version numbers on Github
